export const titles = {
  ITIR: 1,
  OVP: 2,
  PATS: 3,
  PEL: 4,
  PC: 'Настольные ПК',
  NOTEBOOK: 'Ноутбуки',
  MOTHERBOARD: 'Материнские платы',
  RAM: 'Оперативная память',
  ROM: 'Жесткие диски',
  GPU: 'Видеокарты',
  CPU: 'Процессоры',
  OC: 'Операционные системы',
  PROGRAM: 'Программы',
  MONITOR: 'Мониторы',
  KEYBOARD: 'Клавиатуры',
  MOUSE: 'Мыши',
};
